language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    # Repeated to force latest
    - tools
    # The SDK version used to compile your project
    - android-$ANDROID_API
    - android-$ANDROID_EMULATOR_TARGET
    # Emulator
    - sys-img-armeabi-v7a-android-$ANDROID_EMULATOR_TARGET
before_install:
- yes | sdkmanager "platforms;android-28" # This is probably a mistake
- yes | sdkmanager "build-tools;27.0.3" # This is probably a mistake
before_script:
- android list targets
- echo no | android create avd --force -n test -t android-$ANDROID_EMULATOR_TARGET --abi armeabi-v7a
- QEMU_AUDIO_DRV=none emulator -avd test -no-skin -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
env:
  matrix:
    - ANDROID_API=21 ANDROID_EMULATOR_TARGET=21
    - ANDROID_API=28 ANDROID_EMULATOR_TARGET=24
